### ISSUE TITLE
Unable to create session token

### ISSUE THREAD

**Issue by tnation14** [raster-foundry/raster-foundry-docs#18]
On the production site, the `Get Session Token` button is not selectable and cannot generate a Session token, even when a refresh token is entered into the text box. When loading https://docs.rasterfoundry.com, the console shows the error below:
<img width="682" alt="screen shot 2017-05-22 at 9 45 58 am" src="https://cloud.githubusercontent.com/assets/2507188/26312021/39f727d8-3ed4-11e7-8117-92f79d760554.png">

**Comment by notthatbreezy** [comment]
Is the production docs site up to date with staging? The console error isn't on the staging site, but master is behind a bit.

I think we should try doing a deploy to production if we haven't yet.

**Comment by tnation14** [comment]
The prod site should be up to date with staging; I mentioned this issue to @Lknechtli after I did a production deploy on Friday. `Master` is still behind because I didn't want to merge the release branch while this issue persisted.

**Comment by Lknechtli** [comment]
Fixed on Staging and Prod now. Broken on localhost. :disappointed:
