### ISSUE TITLE
Update Jenkins to Pull from Central Spec Repository

### ISSUE THREAD

**Issue by notthatbreezy** [raster-foundry/raster-foundry-docs#27]
The [spec](https://github.com/raster-foundry/raster-foundry-api-spec) repository centralized the spec that gets used across multiple repositories/clients (python, etc). The spec in this repository needs to be removed and when building this project we need to pull down the correct spec.

**Comment by rbreslow** [comment]
@notthatbreezy We're going to be pushing the swagger spec to the S3 bucket in https://github.com/raster-foundry/raster-foundry-api-spec/pull/26, so I believe we can leave this repository as-is:

https://github.com/raster-foundry/raster-foundry-docs/blob/428624ee6d8606bff9185c8681228c56774aec74/src/app/services/swagger.service.ts#L15-L32
